### PR TITLE
Fixed type juggling in equivalentTo()

### LINKED ISSUE #7: The contains expression should not allow type juggling when comparing equivalent expressions
This can do very weird things in some cases. A strict comparison should be used instead (other expressions should be checked for similar cases btw)

### PR DESCRIPTION
**Pull request by webmozart**
Fixes #7

ping @stof

### CODE REVIEW

File: src/Constraint/Contains.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function evaluate($value)
     public function equivalentTo(Expression $other)
     {
         // Since this class is final, we can check with instanceof
-        return $other instanceof $this && $this->comparedValue == $other->comparedValue;
+        return $other instanceof $this && (string) $this->comparedValue === (string) $other->comparedValue;
```
Comment (stof) [inline src/Constraint/Contains.php]: you may even avoid the type casting IMO (or you should do it in the constructor)

Comment (webmozart) [inline src/Constraint/Contains.php]: Avoiding it is not possible, since then the logic of the method is broken. Doing so in the constructor is a good idea though.

Comment (stof) [inline src/Constraint/Contains.php]: Well, your constructor documents that it expects a string. If you actually accept other kind of values without considered it is a user mistake, then the current implementation was indeed buggy, and the casting to string is needed
